-- Migration: Create triggers for automatic timestamp updates
-- Description: Automatically update updated_at column when records are modified
-- Author: Generated by database.md specification
-- Date: 2025-10-22

BEGIN;

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION public.update_updated_at_column() IS 'updated_at 컬럼을 현재 시간으로 자동 업데이트하는 트리거 함수';

-- Create trigger for places table
DROP TRIGGER IF EXISTS trg_places_updated_at ON public.places;
CREATE TRIGGER trg_places_updated_at
  BEFORE UPDATE ON public.places
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TRIGGER trg_places_updated_at ON public.places IS 'places 테이블 수정 시 updated_at 자동 업데이트';

-- Create trigger for reviews table
DROP TRIGGER IF EXISTS trg_reviews_updated_at ON public.reviews;
CREATE TRIGGER trg_reviews_updated_at
  BEFORE UPDATE ON public.reviews
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

COMMENT ON TRIGGER trg_reviews_updated_at ON public.reviews IS 'reviews 테이블 수정 시 updated_at 자동 업데이트';

COMMIT;
